name: evo
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2023.05.30
  - certifi=2022.12.7
  - ld_impl_linux-64=2.38
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=1.1.1v
  - pip=22.3.1
  - python=3.7.16
  - readline=8.2
  - sqlite=3.41.2
  - tk=8.6.12
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
